services:
  frontend:
    build:
      context: .
      target: frontend-final
    container_name: easy-prep-frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      target: backend-final
    container_name: easy-prep-backend
    ports:
      - "3000:3000"
      
